53 car acceptance functionality in the administrator
Gavalencia12/Mobile_Application pull request #84
Opened 2024-11-09 06:45 UTC by Gavalencia12

# <=========== 53 car acceptancer ===========>
## Car acceptance functionality in the administrator

Implementation of Car Acceptance Functionality for Administrators and seller

## Description

- What changes are being made?
A feature has been implemented to allow administrators to review, approve, or reject vehicle listings submitted by users. This ensures that only approved listings are available to buyers, maintaining content quality and compliance with platform standards.
- Why are these changes necessary?
To ensure that all listings on the platform meet the required quality and content standards.
- How have these changes been tested?
Unit and integration tests have been conducted to validate the vehicle review functionality, the approval and rejection interface, and the user notification system.

## List of Changes

1. Database Update:
- Added an approved field to the vehicle table to indicate whether the listing is approved or rejected.

3. Backend Logic for Approval/Reject Process:
- Implemented functionality for administrators to review and make decisions on vehicle listings.
- Logic to store the approval/rejection status and the rejection reason by sending an email to the seller’s user email.

4. Administrator Interface:
- Designed a section in the administrator interface where all pending listings are listed.
- Options for approval and rejection, with an optional field to enter the rejection reason, including email sending, and a button to - access the RePUVE page to check the car’s data.

5. Tests:
- Tests to verify data accuracy, user experience for administrators, email delivery, and to ensure that the seller’s car does not appear in the list of available cars unless approved. Regular users cannot see the car if it is not approved.

## Additional Information
![image](https://github.com/user-attachments/assets/d7c086da-5149-4c90-8bf1-cf195493d365)
![image](https://github.com/user-attachments/assets/c58dfeca-a5c5-469f-a696-573faef136fc)
![image](https://github.com/user-attachments/assets/21e528f3-cc59-415e-bcac-6dcbcff30635)
![image](https://github.com/user-attachments/assets/d3cc0df6-b46a-4772-99e1-0fb44f01471a)
![image](https://github.com/user-attachments/assets/f0a16c93-a890-4657-83c5-97878a7eb8f4)
![image](https://github.com/user-attachments/assets/fc63da80-3ae3-44b1-93ae-79411e4fc03c)

2024-11-09 07:04 UTC, Kamila04 approved these changes
There are some comments in Spanish but everything looks good 👍

2024-11-10 22:07 UTC, Angel591Diaz approved these changes

2024-11-10 23:31 UTC, IsmaelMontiel710 requested changes
In the car review you are not showing the complete car publication with images of the car, with all the information of the car, instead you are grabbing unnecessary information such as when the car was updated, please show all the fields of the car including the images 
of the same

2024-11-10 23:40 UTC, Uli19 approved these changes

2024-11-11 18:13 UTC, merged

2024-11-11 18:13 UTC, MeganPegueros approved these changes